services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
  kmu-pbl-3-team4-backend:
    image: 'sinam7/kmu-pbl-3-team4-backend:latest'
    environment:
      SPRING_PROFILES_ACTIVE: test
      spring:
        datasource:
          url: 'jdbc:mysql://localhost:3306/mysqldb?serverTimezone=UTC&characterEncoding=UTF-8'
    ports:
      - '8080:8080'
  kmu-pbl-3-team4-frontend:
    image: 'dusehd1/front'
    ports:
      - '3000:3000'